-- 알림 Outbox 테이블
CREATE TABLE notification (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id              VARCHAR(255),
    recipient_id          VARCHAR(255) NOT NULL,
    notification_type     VARCHAR(50)  NOT NULL,
    channel               VARCHAR(20)  NOT NULL,
    payload               JSONB,
    status                VARCHAR(20)  NOT NULL,
    retry_count           INT          NOT NULL DEFAULT 0,
    scheduled_at          TIMESTAMPTZ,
    next_retry_at         TIMESTAMPTZ,
    lease_expires_at      TIMESTAMPTZ,
    last_error_code       VARCHAR(50),
    last_error_message    TEXT,
    is_read               BOOLEAN      NOT NULL DEFAULT FALSE,
    read_at               TIMESTAMPTZ,
    created_at            TIMESTAMPTZ  NOT NULL,
    updated_at            TIMESTAMPTZ  NOT NULL,
    -- 중복 발송 방지: 동일 이벤트(event_id+recipient+channel+type) 1건.
    -- event_id가 NULL이면 NULL은 distinct로 취급되어 dedup 대상에서 제외(관리자 단발 발송 허용).
    CONSTRAINT uq_notification_idempotency
        UNIQUE (event_id, recipient_id, channel, notification_type)
);

-- Worker polling: PENDING/FAILED 중 발송 시각이 도래한 행 (partial index로 크기 최적화)
CREATE INDEX idx_notification_polling
    ON notification (status, next_retry_at, scheduled_at)
    WHERE status IN ('PENDING', 'FAILED');

-- Sweeper: PROCESSING 좀비 감지 (lease 만료)
CREATE INDEX idx_notification_sweeper
    ON notification (lease_expires_at)
    WHERE status = 'PROCESSING';

-- 사용자 알림 목록 조회 + 미읽음 카운트
CREATE INDEX idx_notification_recipient
    ON notification (recipient_id, channel, is_read, created_at DESC);

-- DEAD_LETTER 운영 모니터링
CREATE INDEX idx_notification_dead_letter
    ON notification (created_at DESC)
    WHERE status = 'DEAD_LETTER';


-- 알림 템플릿 테이블 (선택 구현: 타입별 메시지 템플릿, 다국어/버전/A-B 확장)
CREATE TABLE notification_template (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_type VARCHAR(50)  NOT NULL,
    channel           VARCHAR(20)  NOT NULL,
    language          VARCHAR(10)  NOT NULL DEFAULT 'ko',
    subject           VARCHAR(200),
    body              TEXT         NOT NULL,
    version           INT          NOT NULL DEFAULT 1,
    is_active         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_template_type_channel_lang_version
        UNIQUE (notification_type, channel, language, version)
);
